[target.x86_64-unknown-linux-gnu]
pre-build = [
  "dpkg --add-architecture arm64 && apt-get update && apt-get install --assume-yes libgtk-3-dev"
]

[target.i686-unknown-linux-gnu]
pre-build = [
  "dpkg --add-architecture i386 && apt-get update && apt-get install --assume-yes libgtk-3-dev:i386"
]

[target.aarch64-unknown-linux-gnu]
pre-build = [
  "dpkg --add-architecture arm64 && apt-get update && apt-get install --assume-yes libgtk-3-dev:arm64"
]
